booking:
  property: Booking Profile Dev Updated
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookingdb
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true